---
AWSTemplateFormatVersion: "2010-09-09"
Description: Deployment configuration for the sqlapi (db only)
Parameters:
  DBUsername:
    Type: String
  DBPassword:
    Type: String
Resources:
  db:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      BackupRetentionPeriod: 0
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: sqlapiServer
      DBName: sqlapi
      Engine: mysql
      MasterUsername:
        Ref: DBUsername
      MasterUserPassword:
        Ref: DBPassword
      PubliclyAccessible: true
Outputs:
  dbaddress:
    Description: address of the created RDS instance
    Value:
      Fn::GetAtt:
        - "db"
        - Endpoint.Address
  dbport:
    Description: port of the created RDS instance
    Value:
      Fn::GetAtt:
        - db
        - Endpoint.Port
